PresentationLayer/Models/ViewModels/HotelsListViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PresentationLayer.Models.ViewModels
{
    public class HotelsListViewModel
    {
        public IEnumerable<HotelViewModel> HotelsList { get; set; }

        public HotelViewModel Hotel { get; set; }

        [Display(Name = "Название отеля")]
        public string Name { get; set; }
    }
}

PresentationLayer/Controllers/UserHomeController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using BLL.DTO;
using BLL.Interfaces;
using PresentationLayer.Models;
using System.Net;
using DAL.Entities.Enumerations;
using PresentationLayer.Models.ViewModels;
using PresentationLayer.Models.ViewModels.VmBuilders.Interfaces;

namespace PresentationLayer.Controllers
{
    [Authorize(Roles = "user")]
    public class UserHomeController : Controller
    {
        private readonly IHotelsManager _hotelsManager;
        private readonly IHotelsVmBuilder _hotelsVmBuilder;

        public UserHomeController(IHotelsManager managersProvider, IHotelsVmBuilder hotelsVmBuilder)
        {
            _hotelsManager = managersProvider;
            _hotelsVmBuilder = hotelsVmBuilder;
        }

        public ActionResult Index()
        {
            IEnumerable<HotelDTO> hotelsDtos = _hotelsManager.GetAll().Take(5);
            Mapper.Initialize(cfg => cfg.CreateMap<HotelDTO, HotelViewModel>());
            var hotels = Mapper.Map<IEnumerable<HotelDTO>, List<HotelViewModel>>(hotelsDtos);

            return View(_hotelsVmBuilder.GeHotelsListViewModel(hotels, new HotelViewModel(), ""));
        }

        [HttpPost]
        public ActionResult Index([Bind(Prefix = "Hotel")]HotelViewModel hotel)
        {
            return View("Create", hotel);
        }



        [HttpPost]
        public ActionResult GetHotels(string Name)
        {
            IEnumerable<HotelDTO> hotelsDtos = _hotelsManager.GetHotelsByName(Name);

            Mapper.Initialize(cfg => cfg.CreateMap<HotelDTO, HotelViewModel>());
            var hotels = Mapper.Map<IEnumerable<HotelDTO>, List<HotelViewModel>>(hotelsDtos).Take(5);

            return PartialView("HotelsList", hotels);
        }

        public ActionResult Create()
        {
            return View();
        }

        // POST: /Default1/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(HotelViewModel hotel)
        {
            if (ModelState.IsValid)
            {
                Mapper.Initialize(cfg => cfg.CreateMap<HotelViewModel, HotelDTO>());

                var hotelDto = Mapper.Map<HotelViewModel, HotelDTO>(hotel);

                _hotelsManager.AddHotel(hotelDto.Name, hotelDto.Location, hotelDto.Category, null);

                return RedirectToAction("Smile");
            }

            return View(hotel);
        }

        public ActionResult Smile()
        {
            return View();
        }
    }
}

PresentationLayer/Views/UserHome/Create.cshtml
@using DAL.Entities.Enumerations
@model PresentationLayer.Models.HotelViewModel

@{
    ViewBag.Title = "Добавление отеля";
}

<h2>Добавление отеля</h2>

@using (Html.BeginForm("Create", "UserHome"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />

        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name, null, new Dictionary<string, object>() { ["class"] = "text-danger none-style-list" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Category, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Category, new SelectList(Enum.GetNames(typeof(CategoryHotel))), new { @class = "selectpicker" })
                @Html.ValidationMessageFor(model => model.Category, null, new Dictionary<string, object>() { ["class"] = "text-danger none-style-list" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Location, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location)
                @Html.ValidationMessageFor(model => model.Location, null, new Dictionary<string, object>() { ["class"] = "text-danger none-style-list" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Добавить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

PresentationLayer/Views/UserHome/HotelsList.cshtml
@model IEnumerable<PresentationLayer.Models.HotelViewModel>

@if (!Model.Any())
{
    <tr>
        <td colspan="3">
            <p>
                <b>Отели не найдены</b>
            </p>
        </td>
    </tr>
}
else
{
    foreach (var hotel in Model)
    {
        <tr>
            <td>@hotel.Name</td>
            <td>@hotel.Category.ToString()</td>
            <td>@hotel.Location</td>
        </tr>
    }
}

PresentationLayer/Views/UserHome/Index.cshtml
@using DAL.Entities.Enumerations
@model PresentationLayer.Models.ViewModels.HotelsListViewModel

@{
    ViewBag.Title = "Index";
    AjaxOptions ajaxOptions = new AjaxOptions()
    {
        UpdateTargetId = "tableBody"
    };
}

<h2>Список отелей</h2>

<div id="searchBox" class="form-horizontal">
    @using (Ajax.BeginForm("GetHotels", null, ajaxOptions, new { id = "search-hotels-form" }))
    {
        <div class="form-group">
            <div class="col-md-10">
                @Html.DisplayNameFor(model => model.Name)
                @Html.TextBoxFor(model => model.Name, new { id = "search-hotels-textbox" })

                <input type="submit" value="Поиск" class="btn btn-default" />

                @Html.ValidationMessageFor(model => model.Name, null, new Dictionary<string, object>() { ["class"] = "text-danger none-style-list" })
            </div>
        </div>
    }
</div>

<div id="hotels-list-container">
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Hotel.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Hotel.Category)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Hotel.Location)
                </th>
                <th></th>
            </tr>
        </thead>

        <tbody id="tableBody">
            @if (string.IsNullOrEmpty(Model.Name))
            {
                @Html.Partial("HotelsList", Model.HotelsList)
            }
        </tbody>

    </table>
</div>


<div id="add-hotel-containter">

    <h4>Добавление отеля</h4>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />

            @Html.ValidationSummary(true)

            <div class="form-group">
                @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Hotel.Name)
                    @Html.ValidationMessageFor(model => model.Hotel.Name, null, new Dictionary<string, object>() { ["class"] = "text-danger none-style-list" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Hotel.Category, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.Hotel.Category, new SelectList(Enum.GetNames(typeof(CategoryHotel))))
                    @Html.ValidationMessageFor(model => model.Hotel.Category, null, new Dictionary<string, object>() { ["class"] = "text-danger none-style-list" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Hotel.Location, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Hotel.Location)
                    @Html.ValidationMessageFor(model => model.Hotel.Location, null, new Dictionary<string, object>() { ["class"] = "text-danger none-style-list" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Добавить" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
</div>

PresentationLayer/Views/UserHome/Smile.cshtml
@{
    ViewBag.Title = "Smile";
}

<h2>Smile</h2>

<div>
    @Html.ActionLink("К списку отелей", "Index", "UserHome")
</div>